# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  pre = "<i class=\"fas fa-laptop\"></i>"
  name = "Posts"
  url = "#posts"
  weight = 20
#<i class=\"fas fa-laptop\"></i>
#[[main]]
#  name = "Projects"
#  url = "#projects"
#  weight = 30

#[[main]]
#  name = "Tutorials"
#  url = "/tutorial/"
#  weight = 50

[[main]]
  pre = "<i class=\"fas fa-envelope\"></i>"
  name = "Contact"
  url = "https://contact.shinydevseries.com"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
